# Generated by Django 3.2.9 on 2023-11-06 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=225, unique=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=225)),
                ('quantite_article', models.PositiveIntegerField()),
                ('type_article', models.CharField(max_length=225)),
                ('image_principale', models.ImageField(default='', upload_to='images/')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieEquipement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(default='', max_length=225)),
                ('pourcentage_rabais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(max_length=225)),
                ('quantite_article', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Routeur',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produit.article')),
                ('fonctionnalite', models.CharField(max_length=225)),
                ('memoire', models.CharField(max_length=225)),
                ('vitesse_du_circuit', models.IntegerField()),
            ],
            bases=('produit.article',),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produit.article')),
                ('fonctionnalite', models.CharField(max_length=225)),
                ('memoire', models.CharField(max_length=225)),
                ('vitesse_du_circuit', models.IntegerField()),
            ],
            bases=('produit.article',),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produit.article')),
                ('couche', models.CharField(max_length=225)),
                ('nombre_port', models.PositiveIntegerField()),
            ],
            bases=('produit.article',),
        ),
        migrations.CreateModel(
            name='PromotionArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.article')),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=225)),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.marque')),
                ('serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.serie')),
            ],
        ),
        migrations.CreateModel(
            name='ImageArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.article')),
            ],
        ),
        migrations.CreateModel(
            name='CategorieArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=225)),
                ('categorie_equipement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.categorieequipement')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categorie_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.categoriearticle'),
        ),
        migrations.AddField(
            model_name='article',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.model'),
        ),
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.stock'),
        ),
    ]
