# Generated by Django 3.2.9 on 2023-10-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compte', '0003_alter_utilisateurpersonalisee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=225)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=225)),
                ('quantite_article', models.PositiveIntegerField()),
                ('type_aticle', models.CharField(max_length=225)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compte.admin')),
            ],
        ),
        migrations.CreateModel(
            name='CategorieEquipement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(max_length=225)),
                ('quantite_article', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Routeur',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produit.article')),
                ('fonctionnalite', models.CharField(max_length=225)),
                ('memoire', models.CharField(max_length=225)),
                ('vitesse_du_circuit', models.IntegerField()),
            ],
            bases=('produit.article',),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produit.article')),
                ('fonctionnalite', models.CharField(max_length=225)),
                ('memoire', models.CharField(max_length=225)),
                ('vitesse_du_circuit', models.IntegerField()),
            ],
            bases=('produit.article',),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produit.article')),
                ('couche', models.CharField(max_length=225)),
                ('nombre_port', models.PositiveIntegerField()),
            ],
            bases=('produit.article',),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=225)),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.marque')),
                ('serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.serie')),
            ],
        ),
        migrations.CreateModel(
            name='CategorieArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=225)),
                ('categorie_equipement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.categorieequipement')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categorie_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.categoriearticle'),
        ),
        migrations.AddField(
            model_name='article',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.model'),
        ),
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.stock'),
        ),
    ]
