# Generated by Django 3.2.9 on 2023-11-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='type_article',
        ),
    ]
