# Generated by Django 3.2.9 on 2023-10-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_promotion_promotionarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='titre',
            field=models.CharField(default='', max_length=225),
        ),
    ]
