# Generated by Django 3.2.9 on 2023-10-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0005_promotion_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionarticle',
            name='statut',
        ),
        migrations.AddField(
            model_name='promotion',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
