# Generated by Django 3.2.9 on 2023-10-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0006_auto_20231023_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_principale',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='ImageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.article')),
            ],
        ),
    ]
