# Generated by Django 3.2.9 on 2023-10-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0007_auto_20231024_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='images',
            field=models.ManyToManyField(to='produit.ImageArticle'),
        ),
        migrations.AlterField(
            model_name='imagearticle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
