# Generated by Django 3.2.9 on 2023-10-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0008_auto_20231024_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='type_aticle',
            new_name='type_article',
        ),
    ]
