# Generated by Django 3.2.9 on 2023-10-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0009_rename_type_aticle_article_type_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='images',
        ),
    ]
