# Generated by Django 3.2.9 on 2023-11-02 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produit', '0010_remove_switch_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_commande', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('nom_destinataire', models.CharField(max_length=225)),
                ('addresse', models.CharField(max_length=225)),
                ('ville', models.CharField(max_length=225)),
                ('pays', models.CharField(max_length=225)),
                ('contact', models.CharField(max_length=225)),
                ('statut', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('quantite', models.PositiveIntegerField()),
                ('statut', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='SocieteExpedition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_transaction', models.CharField(max_length=225)),
                ('montant', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lignes_commande', models.ManyToManyField(to='boutique.LigneCommande')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_facture', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('total', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.commande')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='lignes_commande',
            field=models.ManyToManyField(to='boutique.LigneCommande'),
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.modepaiement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='societe_expedition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.societeexpedition'),
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
