# Generated by Django 3.2.9 on 2023-11-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisateurPersonalisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=30)),
                ('prenom', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('utilisateurpersonalisee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compte.utilisateurpersonalisee')),
            ],
            options={
                'abstract': False,
            },
            bases=('compte.utilisateurpersonalisee',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('utilisateurpersonalisee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compte.utilisateurpersonalisee')),
            ],
            options={
                'abstract': False,
            },
            bases=('compte.utilisateurpersonalisee',),
        ),
        migrations.AddField(
            model_name='utilisateurpersonalisee',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compte.role'),
        ),
    ]
