# Generated by Django 3.2.9 on 2023-10-17 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurpersonalisee',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilisateurpersonalisee',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='utilisateurpersonalisee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateurpersonalisee',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateurpersonalisee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='utilisateurpersonalisee',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
