# Generated by Django 3.2.9 on 2023-10-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_auto_20231017_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurpersonalisee',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
